# Generated by Django 3.0.7 on 2021-09-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_profile_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_portada',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
